### ISSUE TITLE
Different file/folder structure in wasm and TS

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/portablegabi#22]
In the go-wasm part, you are using the approach of having roles for files and on the ts side, you are using objects for folder names. I think this could be made more consistent, by also having role-based folders on the ts side.

**Comment by wischli** [comment]
Currently, we won't change the folder structure. We focused on keeping the **file naming consistent** (ignoring case sensitivity), which is **role-based both in Go and TS**. For Go, we only divide into `wasm` and `non-wasm` directories whereas in TS we need(ed) a different structure.
