### ISSUE TITLE
Extending from String

### ISSUE THREAD

**Issue by tjwelde** [KILTprotocol/portablegabi#23]
https://github.com/KILTprotocol/portablegabi/blob/a5da25351373500fcaf564609c8c4efbf6453d71/src/claim/Credential.ts#L11

It is a bit hard to understand, what's going on, when extending String and putting JSON strings inside. It is a nice optimization, but I would prefer to have clarity first.
So I would suggest not extending String and just saving your stringified JSON (or even the properties of the parsed object?) in a class field.

**Comment by wischli** [comment]
# TODOs

- [ ] Create class `WIP` with methods `parse` and `toString`
- [ ] Extend all listed classes from `WIP`
