### ISSUE TITLE
Fix chain examples

### ISSUE THREAD

**Issue by wischli** [KILTprotocol/portablegabi#35]
After downgrading and adding SDK compatibility, the chain examples do not work anymore due to Alice not having any balance.

```bash
 (node:67925) UnhandledPromiseRejectionWarning: Error: Missing balance for address "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY" with URI/mnemonic //Alice
``` 

We should decide whether want compatibility with both the pallet and the downgraded node or only the latter one @weichweich

**Comment by weichweich** [comment]
only the node. the pallet is discontinued for now. 😅
